version: '2'
services:
  logstash:
    image: logstash
    volumes:
    - ./logstash/config:/config
    - ./logstash/patterns:/opt/logstash/extra_patterns
    networks:
    - logs
    - back
    command: logstash -f /config
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./storage/elasticsearch:/usr/share/elasticsearch/data
    networks:
    - back
  kibana:
    build: kibana/
    volumes:
    - ./kibana/config/:/opt/kibana/config/
    environment:
    - NODE_OPTIONS=--max-old-space-size=200
    networks:
    - back
  web:
    image: nginx
    volumes:
    - ./htpasswd:/etc/nginx/htpasswd
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
    - VIRTUAL_HOST=kibana.${HOSTNAME}
    networks:
    - back
    - lb_web
networks:
  logs:
    driver: bridge
    ipam:
      config:
      - subnet: 192.16.0.0/24
  back:
    driver: bridge
  lb_web:
    external: true
